var products = [
  {
    "product_id": "PR1000",
    "product_name": "KFC Chicken",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "yes",
    "sales_price": "0",
    "cost": "20",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "yes",
  },
  {
    "product_id": "PR1001",
    "product_name": "Italian Pizza",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "60",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1002",
    "product_name": "Bar Soap",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "20",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1003",
    "product_name": "Brookside Milk  1L",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "120",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1004",
    "product_name": "Butter 500g",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "500",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1005",
    "product_name": "Juice 1L",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "120",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
];

var many_products = [
  {
    "product_id": "PR1000",
    "product_name": "KFC Chicken",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "yes",
    "sales_price": "0",
    "cost": "20",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "yes",
  },
  {
    "product_id": "PR1001",
    "product_name": "Italian Pizza",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "60",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1002",
    "product_name": "Bar Soap",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "20",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1003",
    "product_name": "Brookside Milk  1L",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "120",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1004",
    "product_name": "Butter 500g",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "500",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1005",
    "product_name": "Juice 1L",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "120",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1006",
    "product_name": "Cake 1kg",
    "product_type": "consumable",
    "product_category": "PC1002",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "1200",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1007",
    "product_name": "Tomato Sauce 700g",
    "product_type": "consumable",
    "product_category": "PC1006",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "300",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1008",
    "product_name": "Cheese",
    "product_type": "consumable",
    "product_category": "PC1006",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "500",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1009",
    "product_name": "Baking Flour",
    "product_type": "consumable",
    "product_category": "PC1006",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "200",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1010",
    "product_name": "Toothpick",
    "product_type": "consumable",
    "product_category": "PC1008",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "50",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1011",
    "product_name": "Bag",
    "product_type": "consumable",
    "product_category": "PC1009",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "250",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1012",
    "product_name": "Eggs",
    "product_type": "consumable",
    "product_category": "PC1004",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "450",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1013",
    "product_name": "Butter",
    "product_type": "consumable",
    "product_category": "PC1003",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "500",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1014",
    "product_name": "Yeast",
    "product_type": "consumable",
    "product_category": "PC1003",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "70",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1015",
    "product_name": "Rice",
    "product_type": "consumable",
    "product_category": "PC1007",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "700",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1016",
    "product_name": "Plates",
    "product_type": "consumable",
    "product_category": "PC1010",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "300",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1017",
    "product_name": "TV",
    "product_type": "consumable",
    "product_category": "PC1010",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "20,000",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1018",
    "product_name": "Radio",
    "product_type": "consumable",
    "product_category": "PC1011",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "2,000",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1019",
    "product_name": "Table",
    "product_type": "consumable",
    "product_category": "PC1012",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "3,500",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1020",
    "product_name": "Chair",
    "product_type": "consumable",
    "product_category": "PC1012",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "2,500",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
  {
    "product_id": "PR1021",
    "product_name": "Fan",
    "product_type": "consumable",
    "product_category": "PC1012",
    "upc": null,
    "sku": null,
    "income_account": null,
    "expense_account": null,
    "available_in_pos": "no",
    "sales_price": "2,200",
    "cost": "0",
    "weight": "0",
    "volume": "0",
    "vendor_lead_time": "0",
    "customer_lead_time": "0",
    "quantity_on_hand": "0",
    "archived": "no",
  },
];
